### PR TITLE
string manipulation and algo

### PR DESCRIPTION
**Pull request by shivamranj**

### CODE REVIEW

**Review by Ajay-Embed — COMMENTED** [review]
1. Code is zero documented.
2. Variables are not named properly - code is not readable.
3. Make use of classes in C++, create methods & data inside your classes and use data-hiding techniques so that user is not aware of the data which is irrelevant to him. The user in this case will be the driver application (main() routine).
4. Make entries dynamic. If user needs to input something, make it descriptive and dynamic on the console, instead of static allocations inside driver code.

**Review by Ajay-Embed — COMMENTED** [review]
Don't upload binaries. Only .cpp and .h

**Review by Ajay-Embed — COMMENTED** [review]
[https://github.com/Ajay-Embed/DS-and-Algo/blob/master/C/Binary_Trees/binary_tree_iterative.c]

Check this for reference.

**Comment by pran005** [comment]
Hello @shivamranj ,

I'd recommend the following : 

1. Document the algorithm, the purpose of the repo is to explain a newbie what's going on in a lucid way. Explain what a function or code block does.

2. Use a code editor, and don't mix space and tabs. Indent it well. 

3. Use a .gitignore file to avoid uploading binary/unwanted files, if you are aware of their extensions. (For e.g. *.exe, *elf etc.). 

Looking forward to your contribution. 

Regards,
Pranjal

**Pull request closed without merging**
